name: master

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  ezcache:
    runs-on: pipeline_server5
    container:
      image: node:20
    steps:
      - uses: actions/checkout@v4
      - name: Check that dependency installed
        run: |
          yarn install
          yarn ts-jest -v
